version: "3"
services:
  app:

    build: .
    environment:
      DATABASE_URL: postgres://root:pass@postgres:35432/devsource
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  postgres:
    image: postgres:latest

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devsource
    ports: 
      - "35432:5432"  


