version: "3"
services:
  app:

    build: .
    environment:
      DATABASE_URL: postgres://root:password@postgres:5432/devsource
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  postgres:
    image: postgres:latest

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devsource

    ports: 
      - "5432:5432"  


